version: '3.8'

services:

  mariadb:
    image: mariadb:11.3.2
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - ./mariadb/data:/var/lib/mysql
    ports:
      - 3306:3306

  redis:
    image: redis:5.0.14
    volumes:
      - ./redis/data:/data
    ports:
      - 6379:6379

  mongodb:
    image: mongo:7.0.7
    volumes:
      - ./mongodb/data:/data
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    ports:
      - 27017:27017
