version: '3.8'

services:

  mariadb:
    image: mariadb:11.3.2
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - ./mariadb/data:/var/lib/mysql
    ports:
      - 3306:3306
    command: [
      --innodb-buffer-pool-size=8G,
      --innodb-page-size=16K
    ]
    networks:
      - dc-network

  redis:
    image: redis:5.0.14
    volumes:
      - ./redis/data:/data
    ports:
      - 6379:6379
    networks:
      - dc-network

  mongodb:
    image: mongo:7.0.7
    volumes:
      - ./mongodb/data:/data
      - ./mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    ports:
      - 27017:27017
    networks:
      - dc-network

  python:
    image: python:3.9
    container_name: python-script
    volumes:
      - ./mariadb/scripts:/scripts
      - ./mariadb/sql:/sql
    working_dir: /scripts
    depends_on:
      - mariadb
    # Execute the script only if the INIT_SQL environment variable is 'true'
    # Otherwise, do not execute the script
    entrypoint: ["sh", "-c", "if [ \"${INIT_SQL:-false}\" = \"true\" ]; then python initsql.py; else echo 'INIT_SQL is false, skipping python script'; fi"]
    networks:
      - dc-network
networks:
  dc-network:
    driver: bridge
    name: dc-network